### ISSUE TITLE
Error: Cannot find module '../shared'

### ISSUE THREAD

**Issue by aanomm** [north/generator-north#1]
When I install north `npm install -g generator-north` then initiating it `yo north` I end up with the empty directories and the following error.

_\* I have yo and bundler installed_

```
Error: Cannot find module '../shared'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-north/app/index.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by Snugug** [comment]
What version of Node are you running? What version of the North generator are you running? What version of Yo do you have installed?

**Comment by alpyne** [comment]
Same here.

node v0.10.26
generator-north@1.1.0
yo 1.1.2

**Comment by Snugug** [comment]
Try updating to 1.1.1

**Comment by alpyne** [comment]
Same error still here.

**Comment by Snugug** [comment]
Try 1.1.2

For some reason, `shared.js` isn't being picked up in the node package even though it works fine locally. Will need to dig further in at a later date, but for now just manually copied over what was needed for each file.

**Comment by alpyne** [comment]
That did the trick - thanks Sam.

**Comment by Snugug** [comment]
Welcome! Glad it works.

**Comment by Snugug** [comment]
Hey all, can you try updating to 1.2.0 to see if it works, as well as the component and layout generator? I think I've actually future-proof solved this now.
