### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by cmcky** [north/generator-north#4]
When I run 

```
$ npm install -g generator-north
```

then

```
$ yo north
```

I get an error

```
/usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^
Error: Bad argument.
    at process.chdir (/usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14:9)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-north/app/index.js:22:17)
    at EventEmitter.emit (events.js:117:20)
    at callback (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/lib/base.js:365:10)
    at /usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at async.eachSeries (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:130:20)
    at _asyncMap (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:9)
    at Object.mapSeries (/usr/local/lib/node_modules/generator-north
```

**Comment by Snugug** [comment]
73844fba3245530771cde0080b14e064a489603f should solve this. Try updating the global generator

**Comment by cmcky** [comment]
Yup fixed. Thanks!
