### ISSUE TITLE
error on generating

### ISSUE THREAD

**Issue by scottnath** [north/generator-north#8]
ran:

```
yo north
```

error:

```
...
   create north-test/sass/partials/components/.gitkeep
   create north-test/sass/partials/layouts/.gitkeep
   create north-test/sass/enhancements/.gitkeep
   create north-test/sass/fallbacks/.gitkeep

/usr/local/lib/node_modules/generator-north/app/index.js:30
        var npm = this.projectRunner.indexOf('None') !== -1 ? true : false;
                                     ^
TypeError: Cannot call method 'indexOf' of undefined
    at null.<anonymous> (/usr/local/lib/node_modules/generator-north/app/index.js:30:38)
    at EventEmitter.emit (events.js:117:20)
    at callback (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/lib/base.js:365:10)
    at /usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at async.eachSeries (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:130:20)
    at _asyncMap (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:9)
    at Object.mapSeries (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:216:23)
    at Object.async.series (/usr/local/lib/node_modules/generator-north/node_modules/yeoman-generator/node_modules/async/lib/async.js:549:19)
    at runHooks (/usr/local/lib/node_modules/ge%
```

-scott

**Comment by scottnath** [comment]
@Snugug 

And...there's more...

Went to run gulp, got this:

```
$ gulp serve
[gulp] No local gulp install found in ~/development/sites/north-test
[gulp] Try running: npm install gulp
```

installed gulp locally (already was globally). Then got this:

```
$ gulp

module.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-jshint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/scottnath/development/sites/north-test/Gulpfile.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

-scott

**Comment by Snugug** [comment]
Your second problem? You need Gulp installed globally. `npm install -g gulp`
